### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by milkina** [ZlojPes/home_work#13]
1. Пусть метод getChild возвращает обобщенный интерфейс.
2. перегрузить методы takeBook(), returnBook() которые будут принимать переменное количество объектов класса Book

**Comment by ZlojPes** [comment]
1. Об этом хотел спросить на уроке - почему при явно указанном параметризованном списке в интерфейсе Идея с компилятором молча позволяют возвращать обычный список... Или Вы имеете ввиду чтобы метод возвращал не список Composite, а объект, реализующий Composite?
2. Fixed.
