### ISSUE TITLE
Flower

### ISSUE THREAD

**Issue by milkina** [ZlojPes/home_work#17]
1. Добавить геттер, сетер для countryOfOrigin
2. Chrysanthemum - неотформатировано
3. overallCounter - можно подсчитывать в классе Flower.

**Comment by ZlojPes** [comment]
1. Геттер присутствует, сеттер - зачем? Конструктор задает страну при "рождении" цветка. Но добавил
2. В чем неформат? ctrl+alt+L не вносит изменений
3. Спасибо, поправил
