### ISSUE TITLE
Lesson 3. PrintSum

### ISSUE THREAD

**Issue by milkina** [ZlojPes/home_work#5]
1. Блок кода 

 System.out.print("Введите первое слагаемое (целое число)");
        if (scanner.hasNextInt()) {
            i1 = scanner.nextInt();
        } else {
            System.out.print("Вы ввели не целое число!");
            System.exit(1);
        }

повторяется. Вынесите его в отдельный метод.

2. System.exit(1);  - статус кода не равный 0, говорит о том, что программа закончилась с ошибкой. Лучше использовать код 0.

**Comment by ZlojPes** [comment]
Пользователь ввел нецелое число, поэтому и с ошибкой...
