### ISSUE TITLE
Lesson 2. Literals

### ISSUE THREAD

**Issue by milkina** [ZlojPes/home_work#9]
1. Убрать  однострочный комментарий.
2. Документирующий комментарий у вас написан для класса? Поместите его перед объявлением класса.

**Comment by ZlojPes** [comment]
Однострочный комментарий убрал, но ставил я его туда в соответствии с заданием №5:
"Создать программу, в которой используются одно-строчные и много-строчные комментарии."(с)

**Comment by milkina** [comment]
a... Точно.
